### PR TITLE
Enhancement to add refresh token support to fhirclient and allow for checking expiration of a current access token to prematurely exchange for a new access token

### PR DESCRIPTION
**Pull request by zplata**
This enhancement allows consumers of this library to have refresh token support. Previously, applications that consume this library would not have the ability to exchange a refresh token for an access token, and the application would fail the OAuth sequence once refreshed at or past the expiration time span for the access token.

The proposed solution checks on a refresh if the current access token held is >= 120 seconds away from expiration (checking from the payload) and exchanges the refresh token for a valid access token. This exchange also only occurs if the 'online_access' scope is enabled on the application consuming this library. If the current access token held is <= 120 seconds away from the expiration time, it will simply complete a page reload.

### CODE REVIEW

**Comment by isaacvetter** [comment]
👍

**Comment by jmandel** [comment]
Thanks @zplata!

**Comment by jmandel** [comment]
@nschwertner can you help us bump the publication version?

**Comment by nschwertner** [comment]
Published version 0.1.11

**Pull request merged**
