### PR TITLE
Fixes bug that causes error if a Resource has no search parameters

### PR DESCRIPTION
**Pull request by Earthstar**
This fixes an error when I use the updated conformance.json.

### CODE REVIEW

**Comment by jmandel** [comment]
Good catch! Thanks for the report + fix!

BTW, which resources in DSTU2 lack search params altogether? That's new to me.

Since this fix makes sense in the context of our master branch too (not just the dstu2 branch), would you be willing to rebase just this bugfix  onto https://github.com/smart-on-fhir/client-js/master? That would make it easier for us to merge these changes into master + dstu2 directly, rather than as two separate-but-equivalent commits.

(If that sounds like a pain, no problem -- just let me know and I'll handle it manually!)

**Comment by jmandel** [comment]
Thanks for submitting https://github.com/smart-on-fhir/client-js/pull/4 -- I merged that change, so this one shouldn't be needed any longer! Again, good catch!

**Comment by Earthstar** [comment]
Hmm, I'm sure I saw some resources that had no searchParams, but I don't
see any in the

"date": "2014-04-28T17:37:56.075-00:00",
"fhirVersion": "0.1.0",

version of conformance.json. Ah well.

**Comment by jmandel** [comment]
Perhaps some in the 0.4 (DSTU2 draft)?

**Pull request closed without merging**
