### PR TITLE
Update Webpack

### PR DESCRIPTION
**Pull request by JoelV**
update webpack to clean up security warnings from npm audit

### CODE REVIEW

**Comment by jmandel** [comment]
Overall, yes -- though not up to date on pull requests

Will leave this for @vlad-ignatov to evaluate, but I think we would prefer to manage dependency bump PRs that only make changes to the dependency files and allow us to run the build in a subsequent commit to verify outputs.

**Comment by JoelV** [comment]
Ok thanks, the strategy was to start with the webpack and build things. One of the dependency updates had to do with the way a function had to imported as you can see in the PR

**Comment by JoelV** [comment]
ping

**Comment by vlad-ignatov** [comment]
Hi @JoelV ,

Sorry for the delay, I have too many projects to maintain. That said, we just made a huge update to this library that also includes newer Webpack. For reasons too long to explain here, I couldn't use your PR but all the packages have been updated and currently there are zero audit warnings. This has been released as `fhirclient@2.5.0`. I hope it works for you (and please let me know if it doesn't).

**Pull request closed without merging**
