### PR TITLE
Check if host has port before appending from `x-forwarded-port`.

### PR DESCRIPTION
**Pull request by buttercoding**
This addresses the problem mentioned [here](https://github.com/smart-on-fhir/client-js/issues/186)

### CODE REVIEW

**Comment by vlad-ignatov** [comment]
The solution seems fine to me but it is not quite ready for merging. You have done your changes directly to the compiled JS version (which probably solved your problem at runtime). Can you instead try to update `/src/adapters/NodeAdapter.ts` and then run `npm run pack` to build the JS version? Alternatively you can start by running `npm run build:dev` to watch for changes and then just edit TS files and have them compiled automatically.

**Comment by buttercoding** [comment]
OK.  Made edits to the typescript file and rebuilt the repo in the latest commit.

**Comment by vlad-ignatov** [comment]
Hi @buttercoding, Thank you for making this PR. Unfortunately, there were too many issues with it, like NPM scripts converted to Windows, deleted and renamed files, code formatting and tab indentation, all generating a large diff for what should have been one line change. I ended up applying your change myself here https://github.com/smart-on-fhir/client-js/commit/f770b8558a16a95fc99a0e7c8d46f806bbf274bf, and it will be included in the next release. Thank you so much for your collaboration!

**Comment by buttercoding** [comment]
I need to change git settings for line breaks.  Thanks for making the change in another branch.  I'll delete this one.

**Pull request closed without merging**
