### PR TITLE
Expose _noRedirect to adapters as optional parameters when calling au…

### PR DESCRIPTION
**Pull request by dwwinters**
…thorize().

Addresses Issue #121. 

Bumping the minor version number since this introduces a new capability which
*should* be backwards compatible.

The new functionality provided by this commit allows the redirect URL generated
by authorize() to be optionally returned in the promise instead of actually
performing the redirect. This can be useful if an application needs to perform
some actions after authorize() has been called but before the redirect actually
occurs. Testing and debugging is another use case for this change.

Tests all pass, which is expected since _noRedirect already existed for testing
purposes; this commit just exposes it to the adapters. A default boolean value
of false is used, which should help with backward compatibility.

### CODE REVIEW

**Comment by vlad-ignatov** [comment]
Hi @dwwinters,

The `_noRedirect` parameter of `authorize` is only used for testing (so far). That is why I kept it private and undocumented. Can you share a real use case of it, other then testing?

If we were to expose `_noRedirect` to the end user, I think there is a better/cleaner way to that:
1. Remove the 3rd argument of authorize all together
2. Add `noRedirect` option as `noRedirect?: boolean` to https://github.com/smart-on-fhir/client-js/blob/master/src/types.d.ts#L397
3. Describe it in docs
4. Then read it from the options here https://github.com/smart-on-fhir/client-js/blob/master/src/smart.ts#L214, instead of relying on additional argument

All that looks simple but many tests will break and will have to be manually corrected to pass a noRedirect option instead of true as third argument. I could do that myself if tests are bothering you, but I'd prefer to hear more about the use case of that option first.

**Comment by dwwinters** [comment]
Hi @vlad-ignatov

I think there's a lot of value in having this as a parameter the user can set while they're trying to get their apps working with a new server.  Recently I've been trying to integrate an app with a vendor API that deviates from the SMART spec in a couple ways:
- https://github.com/athenahealth/apiserver-athenaFlex/issues/172
- https://github.com/athenahealth/apiserver-athenaFlex/issues/157

Until those issues are fixed, I need a workaround like this so I can continue to make progress with my integration testing.  Ideally setting `noRedirect` to `true` would never be a permanent to solution, just a temporary fix to get around "quirks" like those above.  Does that sound like an acceptable use case for this feature?  If so, I can take a look at your suggestion and update this pull request.  Let me know.

**Comment by vlad-ignatov** [comment]
OK then. Doesn't sound like the most compelling reason to add an option, but I have some future plans and could use that additional flexibility so I'd say give it a try.

**Comment by dwwinters** [comment]
@vlad-ignatov I updated the PR as you requested.  Let me know what you think.

**Comment by vlad-ignatov** [comment]
Thanks @dwwinters ! I will include this in the next release.

**Pull request merged**
