### PR TITLE
Remove jQuery dependency from bb-client

### PR DESCRIPTION
**Pull request by graham-eades**
Summary of Changes:
* Removed the jQuery dependency from `bb-client.js` 
** It was only utilizing the jQuery extend method for object merging. 
** This also removes an unnecessary UI dependency from the authentication and authorization module.
** Didn't want to use Object.assign because only Edge supports it in the MSIE family
** Used impl suggested here: https://github.com/jquery/jquery/issues/3444
* This will allow those using ReactJS to use this library without having to needlessly import jQuery or polyfill jQuery.extend.
* This didn't necessarily need it's own ReactJS adapter since the only shortcoming to using this in ReactJS was the jQuery dependency in `bb-client`.
* Tested using an application that is running in the Cerner CODE environment

### CODE REVIEW

**Comment by graham-eades** [comment]
@nschwertner and @jmandel 
Hey guys, this is a pretty straightforward pull request and would really help those of us using ReactJS out.  This is an awesome client and I just want to do my part by helping out!

**Comment by ivanlebed** [comment]
I don't see any reason why this PR couldn't be merged except for missing tests for the replaced `extend` method?

**Comment by BS062721** [comment]
@vlad-ignatov can me merge this PR? we are developing SMART on FHIR app and facing issue with **jQuery extend** function inside bb-client with ReactJS, this can be helpful.

We tested it locally inside our app and it's working fine.

**Comment by vlad-ignatov** [comment]
Sorry for the late reply. I do support the idea. However, I wonder if you can explain how you use this without jQuery. I though it is required for fhir.js anyway (since we don't have native adapter).

**Comment by vlad-ignatov** [comment]
I was hoping we can find a way to get rid of jQuery all together. Unfortunately, regardless of whether you use it to `extend` or not, it is still included in that huge bundle that your browser needs to download. My question was how do you do those "API calls" and even "authenticate" without jQuery (I think it is being used internally for that, unless I miss something).

That being said, I don't see any easy solution for this.

If you are looking for something lighter that really does not use jQuery, then maybe you can fork https://github.com/smart-on-fhir/client-ts. That will be the future version of this library. It has minimum dependencies and even fhir.js is not included (not bundled). However, is is still in early experimental stage and if want to use it, it is better to just fork it.

**Comment by BS062721** [comment]
@vlad-ignatov Thanks for the info on new FHIR client.

As far as I know, I haven't seen any jQuery code being used while calling or authenticating FHIR API other than whatever is removed in this pull request. (I need to dig deeper to be sure)

But you're correct just removing `extend` won't remove jQuery dependency as whole, but as far as we have tested this code, it works seamlessly for ReactJS integration. `extend` function was the one causing issue with ReactJS.

**Comment by vlad-ignatov** [comment]
Interesting. What issues have you had with `extend` together with React?

**Comment by BS062721** [comment]
@vlad-ignatov Unless, you bundle jQuery with you react application, FhirClient is not able to use any jQuery functions inside it, so jQuery selector `$` and `extend` are undefined for it.

**Comment by vlad-ignatov** [comment]
This PR was a step in the right direction, but not enough to help us avoid old dependencies like jQuery.
Meanwhile, we released a completely rewritten version (that we call v2) that addresses this and many other issues. See http://docs.smarthealthit.org/client-js/ and http://docs.smarthealthit.org/client-js/v2.html.

This PR is now obsolete, so I am closing it and I thank you for the contribution!

**Pull request closed without merging**
