### PR TITLE
Update response type of create function

### PR DESCRIPTION
**Pull request by friedow**
To reflect the API changes to the create function introduced in #86 this PR updates the return type of the create function.

### CODE REVIEW

**Comment by vlad-ignatov** [comment]
Technically speaking, the return type of this method should be `Promise<fhirclient.FHIR.Resource|Response>`. However, this is a tricky thing to get right because it depends on how the server is responding. The goal is to assume that a `Resource` is always returned, and a Response can only be returned in special cases, when the server did not reply as expected. I know this is not currently the case but I will commit a fix soon.

Meanwhile, can you share what server you ran this against and what response are you getting (status code, content-type, location header and body)?

**Comment by friedow** [comment]
I'm working with a hapi fhir server which returns a `ResponseCode: 201`, a `Content-Type: application/fhir+json;charset=UTF-8` and the created resource inside the response body. Since you already submitted the fix to the dev, I'm gonna change the response Type as you suggested :).

**Comment by friedow** [comment]
Furthermore, I added a docstring explaining the alternating response type according to your comment (https://github.com/smart-on-fhir/client-js/pull/86#issuecomment-694871903).

**Comment by vlad-ignatov** [comment]
Thanks @friedow,

I am not sure if this has to merged though. It is technically correct, the comment is right, but the ` | Response` addition to the return type worries me. Even though it is true, it should never happen. In that case, developers should not have to do type checks to see what has been returned. They should just assume that it is a Resource. They shouldn't even care where we got that resource from.

Again, the PR changes are correct but I want to avoid creating confusion. With that said, I think I can either merge the comment changes only, or discard the entire PR. What do you think?

**Comment by friedow** [comment]
I would not merge the comment changes on their own because they could be confusing without the types reflecting them. In my opinion the PR should be merged anyway to reflect the changes introduced in #86. 

However, I totally see your point that this is an edge case and a library design decision at the same time. Since you're the main maintainer, this decision is up to you ;).

**Comment by vlad-ignatov** [comment]
OK. It was not the best design decision and the reason is that we reuse the same underlying request function for all kinds of request methods. I really would prefer not to announce something that should never happen. Thank you for the PR anyways!

**Pull request closed without merging**
