### PR TITLE
Patient context aware request wrapper

### PR DESCRIPTION
**Pull request by nschwertner**
The old JS client used to support patient-context aware FHIR querying via FHIR.js. This was useful functionality which is missing in the current client. I implemented a wrapper for the client.request method mapped to client.patient.request which provides very similar functionality.

### CODE REVIEW

**Comment by vlad-ignatov** [comment]
I want to be extra careful with this one. I think it would be a great addition and personally I would use it the way it is defined now. However, you have described it perfectly in [this](https://github.com/smart-on-fhir/client-js/blob/eaa0f50cf830884e4291d02fcddefa951622faad/src/patient.js#L26-L30) comment.

I am concerned that we might send the wrong message here, releasing something that doesn't always work. This can lead to bugs and issues that can't really be fixed...

Another solution would be to maintain a map of `resourceType`s and their "patient" parameters for each FHIR version (something similar to https://github.com/smart-on-fhir/smart-launcher/blob/master/src/patient-compartment.js). That is a little ugly and I would like to avoid it if possible. Also, the spec may state that certain search parameter exists, but it does not mean that the actual FHIR server supports it...

A more advanced solution could probably parse the conformance statement and check what search parameters are supported for the given resource type. That is of course more complicated so I would avoid it too, unless we don't have another option.

That said, I guess we should at least identify the cases in which this could fail and then evaluate if it is good enough, or if something else needs to be done.

**Comment by nschwertner** [comment]
Wondering if it would make sense to set the default version to `4.0.0` here https://github.com/smart-on-fhir/client-js/pull/57/commits/2039ca74d2e784a65dee6b7b8486294133afe8ed#diff-0522e3105f509814cb6423ddbd93d0b7R22 as a crude way of future-proofing (unknown verisons mapped to R4 although it won't always be correct)?

**Comment by vlad-ignatov** [comment]
It seems that I have confused you a little with that map I gave you. That is a map of patient compartments and I just wanted to show how big it can be. It is not exactly what we need because it shows how a patient can be linked to from within another resource, which is not the same as what the search parameter is. For example, in an Observation resource we might have a `subject` reference but the search parameter is still called `patient`.

I wrote a little script to combine the keys from `r2`, `r3` and `r4` and then remove duplicates and I anded up with:
```js
const patientCompartment = ["Account", "AllergyIntolerance", "Appointment", "AppointmentResponse", "AuditEvent", "Basic", "BodySite", "CarePlan", "Claim", "ClinicalImpression", "Communication", "CommunicationRequest", "Composition", "Condition", "DetectedIssue", "DeviceUseRequest", "DeviceUseStatement", "DiagnosticOrder", "DiagnosticReport", "DocumentManifest", "DocumentReference", "Encounter", "EnrollmentRequest", "EpisodeOfCare", "FamilyMemberHistory", "Flag", "Goal", "Group", "ImagingObjectSelection", "ImagingStudy", "Immunization", "ImmunizationRecommendation", "List", "Media", "MedicationAdministration", "MedicationDispense", "MedicationOrder", "MedicationStatement", "NutritionOrder", "Observation", "Order", "Patient", "Person", "Procedure", "ProcedureRequest", "Provenance", "QuestionnaireResponse", "ReferralRequest", "RelatedPerson", "RiskAssessment", "Schedule", "Specimen", "SupplyDelivery", "SupplyRequest", "VisionPrescription", "AdverseEvent", "CareTeam", "ChargeItem", "ClaimResponse", "Consent", "Coverage", "DeviceRequest", "EligibilityRequest", "ExplanationOfBenefit", "ImagingManifest", "MeasureReport", "MedicationRequest", "RequestGroup", "ResearchSubject", "BodyStructure", "CoverageEligibilityRequest", "CoverageEligibilityResponse", "ImmunizationEvaluation", "Invoice", "MolecularSequence", "ServiceRequest"]
```
That is the list of every resource (regardless of the FHIR version) that we may have to deal with.

The next question is what the name of the search parameter should be. Even if we had a map for that, we don't know if the current server supports it. That said, it seems to me that the approach we can take can more or less look like this:
```js
function getPatientParam(conformance, resourceType) {
    if (patientCompartment.indexOf(resourceType) == -1) throw new Error(`The "${resourceType}" resource cannot be scoped by patient`);
    const meta = conformance.rest[0].resource.find(o => o.type === resourceType);
    if (!meta) throw new Error("Resource not supported");
    if (meta.searchParam.find(x => x.name == "patient")) return "patient";
    if (meta.searchParam.find(x => x.name == "subject")) return "subject";
    // Are there any other possible search params?
    throw new Error("I don't know what param to use");
}
```

**Comment by nschwertner** [comment]
OK. Then perhaps something like this?

**Comment by vlad-ignatov** [comment]
I am optimistic about this! It seems to be working and the last thing that we need to improve is the `getPatientParam` function.

I wrote a simple NodeJS script to test this against real servers. It makes a lot of requests and tests if the server would return an error. The script is now available at https://github.com/smart-on-fhir/client-js/blob/master/test/test.js. I hope you can add the HSPC open endpoints (or any other servers you are testing with) to the `SERVERS` list and see if we can handle them without errors.

Currently it all comes down to [this](https://github.com/smart-on-fhir/client-js/blob/master/test/test.js#L129-L136) list of patient params, but sometimes even the order matters. For example, according to http://hl7.org/fhir/coverage.html there are 5 possible links to a patient - `beneficiary`, `patient`, `payor`, `policy-holder` and `subscriber`! However, in our case a developer is using a call like `client.patient.request(...)`, so we can assume that he is only interested in Patient and not in resources that can also be a `RelatedPerson` or `Organization`. That leaves us with `patient` and `beneficiary`. We must use the first of these two parameters that appears to be supported according to the conformance statement. I think that we need to try with `patient` first and if not available, try with `beneficiary` (that is why the `patient` is listed first). You can see how tricky this is, but it is short and seems to work for the `smarthealthit` servers.

P.S. Any idea how to test this against real EHRs?

**Comment by nschwertner** [comment]
`https://api.logicahealth.org/hspcdemo/open` with patient `SMART-1288992` could be used for HSPC/HAPI testing, for example. I am not sure thought that we'd want a dependency on HSPC in the test scripts.

**Comment by nschwertner** [comment]
Real world EHRs testing is an entirely different beast and had added complexity. Let's leave it as an exercise for another day or contributor.

**Comment by vlad-ignatov** [comment]
Agreed. This test script is not part of the test suite. It is temporary, just for our use, and only intended to "verify" these changes. At least I can't tell if this code is good enough for all the possible resourceTypes and FHIR versions just by looking at it. Running the script however can immediately find if we have missed something (or at least that was the intention).

I can test your endpoint tonight, although I expect it to work because it is HAPI, just like smarthealthit.

**Comment by vlad-ignatov** [comment]
Tested and seems to work fine. I'm about to merge it and then I will write some tests for it and probably optimize it a little to reduce the size. Just one question before I merge - it seems to me that we no longer need the code for detecting the FHIR version, correct?

**Comment by nschwertner** [comment]
No, but it could come in handy in the future.

**Comment by vlad-ignatov** [comment]
That is true. It is now a dead code, but I will add a client method to make use of it.

**Comment by vlad-ignatov** [comment]
Thank you for this! It will be a great addition. I will finish it and include it in the next release.

**Comment by nschwertner** [comment]
Sure thing!

**Comment by vlad-ignatov** [comment]
FYI: This is now released in 2.1.0

**Pull request merged**
