### PR TITLE
Store access token response by state to prevent access token response from being used by multiple instances of SMART apps.

### PR DESCRIPTION
**Pull request by kolkheang**
Depending on how the embedded browser instance is created, sessionStorage can be shared between multiple instances of the browser.  When there are multiple instances of SMART apps running, the sessionStorage is shared among these apps.

Upon inspecting the code further, it looks like the access token response, which contains access token, the refresh token and patient identifier and other data are not stored by state.  

With this change, the tokenResponse is now stored by state in the sessionStorage. The state variable is created each time the SMART app is launched. Now multiple SMART apps can be opened at the same time without any issue regardless of how the embedded browser instance is created and used.

### CODE REVIEW

**Comment by jmandel** [comment]
Thanks @kolkheang. Can you describe where you're seeing this issue with sessionStorage? The way the browser API is defined, sessionStorage should not be shared across browser instances, so embedding state in URL and keying on state should not be required.

We have seen a bug in embedded IE environments (@kpshek may be able to share more details) where unexpected behavior has occurred. Are you seeing this with embedded IE, or elsehwere?

**Comment by kolkheang** [comment]
@jmandel, you're correct.  The defined browser API for sessionStorage should not be shared across tabs.  

Yes, we're seeing this issue in our implementation of the embedded IE.  I've been working with @kpshek on this issue.

**Comment by jmandel** [comment]
Gotcha -  didn't realize you work with @kpshek. There are two issues with this spot fix:

1. It will still fail when the `replaceBrowserHistory` variable is set to false 

2. It pollutes the URL with state variables and will derail apps that rely on HTML5 History API to control the value of the URL. I know PowerChart doesn't show the URL to the user, but most environments do. And in an case this is more than a cosmetic issue because some apps will break. 

Perhaps it would be possible to detect when the client is running inside an embedded IE environment (or specifically within PowerChart -  do you know where the problem originates?) and call a special `unload` handler that rewrites state only at the last possible moment?

**Comment by kpshek** [comment]
An update on this old (1+ yr!) issue...

The need for this change is due to specific behavior of the embedded IE browser. Microsoft documents that each instance of their embedded IE browser must be instantiated within it's own thread. If this is not done and instances of the embedded IE browser are instead created in a shared thread, then state is shared between browser instances. Crucially here, this includes the HTML5 sessionStorage API implementation. This behavior is contrary to the documentation of the [sessionStorage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) in which the data is normally guaranteed to be isolated per tab/window.

Today, Cerner's EHR instantiates embedded IE browser instances on a single thread. Here's a real-world practical issue we saw prior to using the proposed fix:

Within the EHR...
1. Open SMART app A on patient P1
2. Open SMART app B on patient P2
3. Refresh SMART app A -- it obtains/shows data for patient P2 rather than P1 since the the patient context and access token stored in sessionStorage is shared between the two SMART apps. The last write to sessionStorage is what is used.

😞

We've been using and instructing SMART app developers running within Cerner's EHR to use this patch over the past year. We're now (finally) circling back on this to get a modified version of this patch incorporated into main/upstream project here. @kolkheang is working on this now and will have an updated patch here soon.

I reached out to a few other large EHR vendors which I know also embed SMART webapps within a native Windows application using the embedded IE browser (just like Cerner). I wanted to know if they too were affected by this issue and asked them to run a simple test page to demonstrate the issue. One very large EHR vendor responded back and confirmed they too have the same issue. I'm withholding names of the organizations to respect whatever their issue disclosure policy may be.

Our modified proposed fix for this issue is going to utilize a setting within BBClient that enables this behavior or keying sessionStorage data by the state and passing state within the URL. By default, the behavior will be as it is today; that is, it will default to assuming it is in an environment where sessionStorage is implemented per expectations (data isolation between tab/window). When running within PowerChart, we'll flip this flag to use the alternate aforementioned behavior.

Anyway, I just wanted to update everyone here and to watch for an update from @kolkheang soon.

**Comment by kolkheang** [comment]
Thanks @kpshek for a very detail update!  I've created pr #13 to resolve this issue.  I'm going to close this pr in favor of pr #13.

**Pull request closed without merging**
