### PR TITLE
Add support for PKCE and JWK-based authentication

### PR DESCRIPTION
**Pull request by jmandel**
Updates based on the 2021-09 FHIR connectathon, closing in on the SMARTv2 spec.

This is a "second attempt", removing the `node-jose` dependency and leveraging SubtleCrypto (built into current Node and current browsers; we need to decide if that's an acceptable constraint, but given that these are new features and the library should work against SMARTv1 servers without them, I think that's probably OK)

### CODE REVIEW

**Comment by jmandel** [comment]
https://www.npmjs.com/package/jose is a better dependency -- worth using in place of creating JWS manually

**Comment by vlad-ignatov** [comment]
It seems to me that one major concern here is the bundle size. We can do this using `window.ctypto` and/or node packages like `crypto`, or `node-jose` or `jose`. There are even few things that can be done directly, without introducing external dependencies. For example, parsing a JWTs is currently done manually, just because they are not verified and using additional packages (like `jsonwebtoken`) could be omitted.

Maintaining small bundle size is hard but fortunately this library has some ways to deal with that. Those are not obvious though, so let me describe them here.

1. First and foremost we have the "adapters". Those are classes that act as collections of environment-specific methods.   They are ideal for functionality that needs to be implemented differently in different environments (like using `jose` in Node   and web crypto in browsers). For example, you may have a `generatePKCECodes` method added to both   `src/adapters/BrowserAdapter.ts` and `src/adapters/NodeAdapter.ts`. The browser implementation could use crypto similar   to what you did in your first commits, and the node implementation can use Jose as you did it in later. Then the entire thing should NOT impact the bundle size too much because:
    - The node implementation is not included in the bundle. 
    - The browser implementation relies on `window.crypto` so there is nothing that needs to be added (unless we target an   older browser, which is controlled [by this list](https://github.com/smart-on-fhir/client-js/blob/master/dist/package.json#L33-L38)).
 
    A while back I started integrating some of your changes using this "adapter approach" [here](https://github.com/smart-on-fhir/client-js/commit/f59fbf3055cd1d430d886ad0c786b96bca178f38). With that said, unless there is any functionality here that cannot be implemented using web crypto, I see no reason to include additional packages in the bundle.

2. Both `node-jose` and `jose` have util functions for base64url encoding and decoding so there is no need to include the `base64url ` package either. That can also go in adapters like [here](https://github.com/smart-on-fhir/client-js/blob/PKCE/src/adapters/BrowserAdapter.ts#L149) and and a corresponding method can be added to the node adapter, using `jose.util.base64`...

3. Finally, another way to reduce the bundle size is to avoid `async` functions. This is a little odd so let me explain:
Sometimes we have functions (or methods) that happen to return a promise. In such case the developer is tempted to put `async ` in-front of it and some IDEs like VSCode even recommend doing so. However, Babel uses bulky transform for async functions that augments the code a lot! That is why, until we stop targeting browser without native async support, I recommend the following:
- For simple cases where a function returns a promise directly (eg: `async () => somePromise`) - do not use `async` or remove it if used already
- If the function is doing something before returning a promise, wrap everything in a promise and return it immediately without `async`
- Finally, in some case this might be too complicated or decrease readability. If so, use `async ` but keep an eye on the bundle size.


P.S. After every build, some heat maps are generated for every bundle. Those are the html files in `/dist/build/` and they are a great way to visually track what is included in the build.

**Comment by jmandel** [comment]
Thanks!Do you have specific target sizes in mind, so we can tell how the V2 feature weighs against these targets? Also if you think it's important, should we offer different builds that support different feature sets? (I'd rather avoid this because it's likely that developers will want to incrementally adopt SMARTv2 features as servers support them, but happy to explore the possibility.)

**Comment by jmandel** [comment]
>There are even few things that can be done directly, without introducing external dependencies.

The current branch shouldn't include any external JWT dependencies (though I think it's worth adding one, as noted above)

**Comment by vlad-ignatov** [comment]
> There are even few things that can be done directly, without introducing external dependencies.

I was just trying to explain why functions like [this](https://github.com/smart-on-fhir/client-js/blob/master/src/lib.ts#L289) exist in the current version.

From the jose README:
> node-jose is built to work in any javascript runtime, to be able to do that it packs a lot of polyfills and javascript implementation code in the form of [node-forge](https://github.com/digitalbazaar/forge), this significantly increases the footprint of the modules with dependencies that either aren't ever used or have native implementation available in the runtime already, those are often times faster and more reliable.

So they are saying that `jose` will use `window.crypto` if available. I have not used `jose` so far and I wonder how they are doing that. Will `jose` add some crypto package to the bundle? Or will it depend on the `browserslist` field in package.json? It's worth exploring if needed.

**Comment by vlad-ignatov** [comment]
Regarding sizes - no, I don't have anything specific in mind and I'm not a fan of the idea of having different builds. We already have several different builds (files containing "pure" have no polyfills and are for people who know they won't be dealing with IE). Some day IE will be discontinued in all EHRs and we will automatically get a significant size reduction.

As for the comparison:
The latest build ([here](https://github.com/smart-on-fhir/client-js/blob/ddb0e8b8f0148d7f7511c8022d2519b11334b605/dist/build/fhir-client.min.js)) is 595 KB, while the latest production build ([here](https://github.com/smart-on-fhir/client-js/blob/master/dist/build/fhir-client.min.js)) is 133 KB. This means the bundle is now more than 4.5X bigger, which is worth investigating. It is easy to spot the difference if you look at https://github.com/smart-on-fhir/client-js/blob/ddb0e8b8f0148d7f7511c8022d2519b11334b605/dist/build/fhir-client.min.js. All those Crypto and Buffer stuff are included too. That is why I was suggesting different approach that should not include crypto or jose or even base64url.

**Comment by jmandel** [comment]
Ahh. The direct comparison would be with https://github.com/microsoft-healthcare-madison/client-js/blob/own-jws/dist/build/fhir-client.min.js -- that is the version of this minified file in the latest commit on this pull request, no? And it looks like *177# kilobytes (not 595). I think if we start from there and add in a `jose` dependency, the size should be pretty stable.

**Comment by vlad-ignatov** [comment]
Aha, my mistake. 177 looks much better! 

I can't say I fully understand all the changes though. Perhaps you can switch to `jose` and then I can give it a try and maybe micro optimize it here and there. Right now it appears that `security/index.ts` may be causing `Buffer` to be included in the bundle. Whatever the idea is, that will probably change after `jose` is in use.

**Comment by nschwertner** [comment]
Take a look at https://github.com/tonyxu-io/pkce-generator/blob/master/index.html It looks like it can be done with just crypto.js

**Comment by jmandel** [comment]
Yeah (note that's a 50kb minified/uncompressed dependency; libs like https://www.npmjs.com/package/pkce-pair are ~10kb)

**Comment by jmandel** [comment]
Closing in favor of https://github.com/smart-on-fhir/client-js/pull/147

**Pull request closed without merging**
